[package]
name = "native-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
town = { package = "town", path = "../.." }
bevy = { version = "0.8", default-features = false }
image = "0.24.5"
winit = "0.26.1"
